module.exports = {
  APIname: "Appalti190",
  email: {
    to: "marcosolari@gmail.com",
    from: "appalti190mailer <marcosolari@gmail.com>",
    subject: "Appalti190 {{level}}",
    host: "smtp.gmail.com",
    username: "marcosolari@gmail.com",
    password: "dpevuufaijfhhqyu",
    ssl: true,
  },
  emailAdministration: {
    from: "marcosolari+2@gmail.com",
    to: "marcosolari@gmail.com",
  },
  envRequiredVariables: [ // TODO: check all of these are necessary
    "JWT_ACCESS_TOKEN_SECRET",
    "JWT_REFRESH_TOKEN_SECRET",
    "JWT_ACCESS_TOKEN_EXPIRY",
    "JWT_REFRESH_TOKEN_EXPIRY",
    "MONGO_SCHEME",
    "MONGO_URL",
    "MONGO_DB",
    "MONGO_USER",
    "MONGO_PASS",
    "CLOUD_NAME",
    "CLOUD_API_KEY",
    "CLOUD_API_SECRET",
    "FROM_EMAIL",
    "GOOGLE_OAUTH_CLIENT_ID",
    "GOOGLE_OAUTH_CLIENT_SECRET",
    "FACEBOOK_OAUTH_CLIENT_ID",
    "FACEBOOK_OAUTH_SECRET_KEY",
    "SENDGRID_API_KEY",
    "STRIPE_API_KEY_DEV",
    "STRIPE_API_KEY_LIVE",
    "AWS_BUCKET_NAME",
    "AWS_REGION",
    "AWS_ACCESS_KEY_ID",
    "AWS_SECRET_ACCESS_KEY",
  ],
};
